---
- name: Upgrade Step 1
  hosts: wave1

  vars:
       UserName: admin
       Password: yourpasswordhere
       provider:
         password: "{{ Password }}"
         server: "{{ ansible_host }}"
         user: "{{ UserName }}"
         validate_certs: false
       InstallISO: /root/F5-Ansible-Toolbox/images/BIGIP-15.1.5.1-0.0.14.iso

  tasks:

#copies the image "InstallImage" to /shared/images on the target device(s)
    - name: Copy Image "{{ InstallImage }}"
      bigip_software_image:
        image: "{{ InstallISO }}"
        provider: "{{ provider }}"
      delegate_to: localhost
...
