---
- name: Upgrade Step 1
  hosts: wave1

  vars:
       UserName: admin
       Password: yourpasswordhere
       provider:
         password: "{{ Password }}"
         server: "{{ ansible_host }}"
         user: "{{ UserName }}"
         validate_certs: false
       InstallImage: /root/bigip-upgrades/images/BIGIP-15.1.5.1-0.0.14.iso
#       InstallImage: /root/bigip-upgrades/images/BIGIP-16.1.2.2-0.0.28.iso
  tasks:

#copies the image "InstallImage" to /shared/images on the target device(s)
    - name: Copy Image "{{ InstallImage }}"
      bigip_software_image:
        image: "{{ InstallImage }}"
        provider: "{{ provider }}"
      delegate_to: localhost
...
