---
- name: Upgrade Step 2
  hosts: wave1

  vars:
       UserName: admin
       Password: yourpasswordhere
       provider:
         password: "{{ Password }}"
         server: "{{ ansible_host }}"
         user: "{{ UserName }}"
         validate_certs: false
       InstallVolume: HD1.2
       InstallImage: BIGIP-15.1.5.1-0.0.14.iso
#       InstallImage: BIGIP-16.1.2.2-0.0.28.iso

  tasks:
   - name: Notice of long running task.
     debug:
       msg: "The next task will appear to be stalled or hung, with no output, while the installation progresses on the BIG IPs. To monitor the status of the installation, review the devices' install progress in the devices' TMUI"

   - name: Install image in specified volume, but do not activate the volume
     bigip_software_install:
       image: "{{ InstallImage }}"
       volume: "{{ InstallVolume }}"
       state: installed
       provider: "{{ provider }}"
     delegate_to: localhost

#when: failover_state.stdout  == 'standby'

...
